### ISSUE TITLE
global variables as params

### ISSUE THREAD

**Issue by lucasrenan** [simanek/Heads-Up-Grid#1]
global variables is a big famous problem, so I think that you should have a way to configure without using global variables. maybe passing a json to `makehugrid`.
what do you think about it?

**Comment by simanek** [comment]
Hi Lucas,

I really, truly am a novice with javascript. 

With that said, would the most popular response on this page be the best way to improve the Heads-Up Grid code?

http://stackoverflow.com/questions/2613310/ive-heard-global-variables-are-bad-what-alternative-solution-should-i-use

**Comment by lucasrenan** [comment]
http://stackoverflow.com/a/2613534/210512

this is a good one to structure your plugin :)

**Comment by simanek** [comment]
Hmmm... OK. I'm pretty sure I can figure this out, but since I don't really understand all of the details, would you say that the new fancybox is a good example of how to configure without using global variables? 

http://fancyapps.com/fancybox/

If not, I really just need an example to see all of the ins-and-outs. That's how I learned everything I know about HTML + CSS and is the reason I struggle with javascript. Frequently people discussing js make broad assumptions about the programming background of the reader. And I have no programming background. :D

What mwilcox says on that stackoverflow page makes sense but I don't really understand all of the implications. With a good example I could emulate it.

**Comment by simanek** [comment]
And thank you very much for taking the time to help me improve this!

**Comment by lucasrenan** [comment]
I will send a pull request soon :)

**Comment by simanek** [comment]
Hi Lucas, I was curious if this commit to follow JQuery plugin standards has addressed this global variable problem. 

https://github.com/simanek/Heads-Up-Grid/pull/3

Perhaps me asking this question illustrates how little I understand about how JavaScript works. ;)

**Comment by lucasrenan** [comment]
I guess that's ok.. I'll test the changes.. but I think that you should close this issue for now :)
